definitions:
  models.UserInfo:
    properties:
      birthday:
        type: string
      job:
        type: string
      sex:
        type: string
    type: object
  openapi.CreateUserRes:
    type: object
info:
  contact: {}
  description: go lang gin web swager demo
  termsOfService: http://127.0.0.1:8080
  title: swageer demo
  version: "3.0"
paths:
  /get_user_info:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserInfo'
      summary: get user info by name
  /user:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/openapi.CreateUserRes'
      summary: create user
swagger: "2.0"
